//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NSPecor.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BC_DP_SITIOS_UPME
    {
        public BC_DP_SITIOS_UPME()
        {
            this.MUB_VSS = new HashSet<MUB_VSS>();
            this.MUB_PECOR_CP_VSS = new HashSet<MUB_PECOR_CP_VSS>();
        }
    
        public decimal OBJECTID { get; set; }
        public int ID_CENTRO_POBLADO { get; set; }
        public string COD_CP_UPME { get; set; }
        public string COD_DPTO { get; set; }
        public string COD_MPIO { get; set; }
        public string COD_SITIO { get; set; }
        public int ID_FUENTE_CP { get; set; }
        public string NOMBRE_SITIO { get; set; }
        public int ID_TIPO { get; set; }
        public int ID_CLASE { get; set; }
        public Nullable<System.DateTime> FECHA_OFICIALIZACION { get; set; }
        public Nullable<int> ID_USUARIO_OFICIALIZACION { get; set; }
        public string OBSERVACION { get; set; }
        public Nullable<System.DateTime> FECHA_DATO { get; set; }
        public decimal LONGITUD { get; set; }
        public decimal LATITUD { get; set; }
        public Nullable<decimal> ALTITUD { get; set; }
        public int ACTIVO { get; set; }
    
        public virtual ICollection<MUB_VSS> MUB_VSS { get; set; }
        public virtual ICollection<MUB_PECOR_CP_VSS> MUB_PECOR_CP_VSS { get; set; }
        public virtual VISTA_BC_MPIO_DPTO VISTA_BC_MPIO_DPTO { get; set; }
    }
}
