//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NSPecor.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MUB_USUARIOS_ORG
    {
        public long ID_USUARIO_ORG { get; set; }
        public long ID_ORGANIZACION { get; set; }
        public long ID_CENTRO_POBLADO { get; set; }
        public Nullable<long> USUARIOS_URBANOS { get; set; }
        public Nullable<long> USUARIOS_RURAL { get; set; }
        public Nullable<long> VSS_URBANO { get; set; }
        public Nullable<long> VSS_RURAL { get; set; }
        public Nullable<System.DateTime> FUENTE_REGISTRO { get; set; }
        public Nullable<long> ID_USUARIO_REGISTRO { get; set; }
        public Nullable<System.DateTime> FECHA_ACTUALIZACION { get; set; }
        public string OBSERVACION { get; set; }
    
        public virtual MUB_ORGANIZACIONES MUB_ORGANIZACIONES { get; set; }
    }
}
