//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NSPecor.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    
    public partial class MUB_PECOR_CP_VSS
    {
        public long ID_PROYECTO_PECOR { get; set; }
        [DisplayName("CENTRO POBLADO")]
        public int ID_CENTRO_POBLADO { get; set; }
        [DisplayName("VIVIENDAS BENEFICIADAS")]
        public Nullable<decimal> VSS_BENEF { get; set; }
        public Nullable<decimal> DEMANDA_ANUAL { get; set; }
        [Key]
        public long ID_CP_PY { get; set; }
    
        public virtual BC_DP_SITIOS_UPME BC_DP_SITIOS_UPME { get; set; }
        public virtual MUB_PROYECTOS_PECOR MUB_PROYECTOS_PECOR { get; set; }
    }
}
