//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NSPecor.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MUB_GENERALES
    {
        public long ID_PARAMETROS { get; set; }
        public long ID_MODULOS { get; set; }
        public long ID_GRUPO { get; set; }
        public long ID_UNIDAD { get; set; }
        public Nullable<byte> ORDEN_GRUPO { get; set; }
        public string PARAMETRO { get; set; }
        public string DESCRIPCION { get; set; }
        public string VALOR { get; set; }
        public Nullable<long> ANO_VIGENCIA { get; set; }
        public string ESTADO { get; set; }
    }
}
