//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NSPecor.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MUB_ROL_PRIVILEGIOS
    {
        public long ID_ROL_PRIVILEGIO { get; set; }
        public decimal ID_ROL { get; set; }
        public string INSERT { get; set; }
        public string UPDATE { get; set; }
        public string DELETE { get; set; }
        public string QUERYS { get; set; }
        public Nullable<long> ID_USUARIO_ACTUALIZACION { get; set; }
        public Nullable<System.DateTime> FECHA_ACTUALIZACION { get; set; }
    
        public virtual MUB_PRIVILEGIOS MUB_PRIVILEGIOS { get; set; }
        public virtual MUB_ROL MUB_ROL { get; set; }
    }
}
