//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NSPecor.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MUB_PRIVILEGIOS
    {
        public MUB_PRIVILEGIOS()
        {
            this.MUB_ROL_PRIVILEGIOS = new HashSet<MUB_ROL_PRIVILEGIOS>();
        }
    
        public long ID_PRIVILEGIO { get; set; }
        public string DESCRIPCION { get; set; }
        public Nullable<long> ID_USUARIO_ACTUALIZACION { get; set; }
        public Nullable<System.DateTime> FECHA_ACTUALIZACION { get; set; }
    
        public virtual ICollection<MUB_ROL_PRIVILEGIOS> MUB_ROL_PRIVILEGIOS { get; set; }
    }
}
