//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NSPecor.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    public partial class MUB_ORGANIZACIONES
    {
        public MUB_ORGANIZACIONES()
        {
            this.MUB_PROYECTOS_PECOR = new HashSet<MUB_PROYECTOS_PECOR>();
            this.MUB_USUARIOS_ORG = new HashSet<MUB_USUARIOS_ORG>();
            this.MUB_USUARIOS = new HashSet<MUB_USUARIOS>();
        }
        [Key]
        public long ID_ORGANIZACION { get; set; }
        [Required]
        public string NIT { get; set; }
        [DisplayName("RAZÓN SOCIAL")]
        [Required]
        public string RAZON_SOCIAL { get; set; }
        [DisplayName("DIRECCIÓN")]
        public string DIRECCION { get; set; }
        [DisplayName("TELÉFONO")]
        public string TELEFONO { get; set; }
        public string REPRESENTANTE { get; set; }
        [DisplayName("TIPO ORGANIZACIÓN")]
        public long ID_TIPO_ORGANIZACION { get; set; }
        [Required]
        public string SIGLA { get; set; }
        public string MP_UPME { get; set; }
        public Nullable<long> ID_AREA_DISTRIBUCION { get; set; }
        public string CODIGO { get; set; }
        public long ACTIVO { get; set; }
    
        public virtual MUB_TIPO_ORGANIZACION MUB_TIPO_ORGANIZACION { get; set; }
        public virtual ICollection<MUB_PROYECTOS_PECOR> MUB_PROYECTOS_PECOR { get; set; }
        public virtual ICollection<MUB_USUARIOS_ORG> MUB_USUARIOS_ORG { get; set; }
        public virtual ICollection<MUB_USUARIOS> MUB_USUARIOS { get; set; }
    }
}
