//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NSPecor.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MUB_TIPO_ORGANIZACION
    {
        public MUB_TIPO_ORGANIZACION()
        {
            this.MUB_ORGANIZACIONES = new HashSet<MUB_ORGANIZACIONES>();
        }
    
        public long ID_TIPO_ORGANIZACION { get; set; }
        public string NOM_TIPO_ORG { get; set; }
        public string ACTIVO { get; set; }
    
        public virtual ICollection<MUB_ORGANIZACIONES> MUB_ORGANIZACIONES { get; set; }
    }
}
