//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NSPecor.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MUB_ROL
    {
        public MUB_ROL()
        {
            this.MUB_ROL_PRIVILEGIOS = new HashSet<MUB_ROL_PRIVILEGIOS>();
            this.MUB_USUARIOS_ROLES = new HashSet<MUB_USUARIOS_ROLES>();
        }
    
        public decimal ID_ROL { get; set; }
        public string NOMBRE { get; set; }
        public long ID_MODULO { get; set; }
    
        public virtual MUB_MODULOS MUB_MODULOS { get; set; }
        public virtual ICollection<MUB_ROL_PRIVILEGIOS> MUB_ROL_PRIVILEGIOS { get; set; }
        public virtual ICollection<MUB_USUARIOS_ROLES> MUB_USUARIOS_ROLES { get; set; }
    }
}
