//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NSPecor.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MUB_USUARIOS_ROLES
    {
        public long ID_USUARIO { get; set; }
        public decimal ID_ROL { get; set; }
        public Nullable<System.DateTime> FECHA_ACTUALIZACION { get; set; }
        public long ID_USR_ROL { get; set; }
    
        public virtual MUB_ROL MUB_ROL { get; set; }
        public virtual MUB_USUARIOS MUB_USUARIOS { get; set; }
    }
}
