//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NSPecor.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MUB_GRUPOS
    {
        public long ID_GRUPO { get; set; }
        public Nullable<long> ID_MODULO { get; set; }
        public string DESCRIPCION { get; set; }
    }
}
