//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NSPecor.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MUB_MODULOS
    {
        public MUB_MODULOS()
        {
            this.MUB_ROL = new HashSet<MUB_ROL>();
        }
    
        public long ID_MODULO { get; set; }
        public string DESCRIPCION { get; set; }
    
        public virtual ICollection<MUB_ROL> MUB_ROL { get; set; }
    }
}
