//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NSPecor.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MUB_UNIDADES
    {
        public long ID_UNIDAD { get; set; }
        public string UNIDAD { get; set; }
        public string UNI_DESCRIPCION { get; set; }
    }
}
