//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NSPecor.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VISTA_SUBESTACION
    {
        public VISTA_SUBESTACION()
        {
            this.MUB_PROYECTOS_PECOR = new HashSet<MUB_PROYECTOS_PECOR>();
        }
    
        public decimal OBJECTID { get; set; }
        public decimal ID_SUBESTACION { get; set; }
        public string COD_SUB_UPME { get; set; }
        public decimal ID_CONTACTO { get; set; }
        public decimal ID_ORGANIZACION { get; set; }
        public string NOM_SUBESTACION { get; set; }
        public Nullable<short> ID_NIVEL_TENSION { get; set; }
        public short ID_TENSION_SUB { get; set; }
        public string AMPLIACION { get; set; }
        public short ID_ESTADO_SUB { get; set; }
        public Nullable<System.DateTime> FECHA_OPERACION { get; set; }
        public System.DateTime FECHA_CORTE_UPME { get; set; }
        public string OBSERVACION { get; set; }
        public string COD_DPTO { get; set; }
        public string COD_MPIO { get; set; }
        public decimal LATITUD { get; set; }
        public decimal LONGITUD { get; set; }
        public Nullable<decimal> ALTITUD { get; set; }
        public string ACTIVO { get; set; }
        public decimal PORCENTAJE_CARGA { get; set; }
        public decimal CAPACIDAD_MVA { get; set; }
        public Nullable<System.DateTime> FECHA_OFICIALIZACION { get; set; }
        public Nullable<decimal> ID_USUARIO_OFICIALIZA { get; set; }
    
        public virtual ICollection<MUB_PROYECTOS_PECOR> MUB_PROYECTOS_PECOR { get; set; }
    }
}
