//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NSPecor.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VISTA_BC_MPIO_DPTO
    {
        public VISTA_BC_MPIO_DPTO()
        {
            this.BC_DP_SITIOS_UPME = new HashSet<BC_DP_SITIOS_UPME>();
        }
    
        public long OBJECTID_1 { get; set; }
        public string DPTO_CCDGO { get; set; }
        public string DPTO_CNMBR { get; set; }
        public string MPIO_CCDGO { get; set; }
        public string MPIO_CNMBR { get; set; }
        public string MPIO_CNMBRSA { get; set; }
    
        public virtual ICollection<BC_DP_SITIOS_UPME> BC_DP_SITIOS_UPME { get; set; }
    }
}
